//! OpenAPI 3.1 spec for the `/api/v1` REST surface.
//!
//! The `ApiDoc` struct collects every `#[utoipa::path]`-annotated handler and
//! every `ToSchema`-deriving DTO into a single `utoipa::OpenApi` value. The
//! spec is served at `/api/v1/openapi.json` by [`router`] — deliberately
//! *outside* the scope-gated sub-routers so tooling (Swagger UI, client
//! codegen, CI lint) can fetch it without a bearer token. The spec only
//! describes shapes, not secrets; callers still need `mcp:read` / `mcp:admin`
//! to actually hit the documented endpoints.

use axum::routing::get;
use axum::{Json, Router};
use utoipa::OpenApi;

use crate::api_key_profiles;
use crate::audit;
use crate::break_glass;
use crate::builtins;
use crate::catalog;
use crate::change_requests;
use crate::confidential_clients;
use crate::error::ApiErrorBody;
use crate::federated_peers;
use crate::inspection_rules;
use crate::manifest_bundles;
use crate::oauth_consent;
use crate::policies;
use crate::policy_bundles;
use crate::rate_limit_policies;
use crate::rbac;
use crate::servers;
use crate::tasks;
use crate::tenants;
use crate::upstream_sessions;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "Waygate Admin API",
        version = env!("CARGO_PKG_VERSION"),
        description = "Admin surface for upstream manifests, Cedar policies, audit events, and \
                       human-in-the-loop control-plane change requests. Each endpoint is gated by a \
                       Bearer token carrying the scope named in its per-route docs — `mcp:read` \
                       (servers), `mcp:admin` (most admin mutations), or `mcp:propose` (the \
                       change-request maker surface) — against the gateway's OAuth \
                       resource-server metadata.",
    ),
    paths(
        servers::list_servers,
        builtins::list_builtins,
        servers::get_server,
        servers::list_tools,
        servers::reconnect_server,
        servers::refresh_server_catalog,
        servers::get_quarantine,
        servers::clear_quarantine,
        policies::list_policies,
        policies::simulate,
        audit::list_audit,
        audit::list_decisions,
        audit::get_decision,
        crate::audit_verify::verify_chain,
        crate::audit_routing::list_routing,
        crate::audit_routing::upsert_routing,
        crate::audit_routing::delete_routing,
        crate::audit_retention::list_retention,
        crate::audit_retention::upsert_retention,
        crate::audit_retention::delete_retention,
        crate::audit_sweep::run_sweep,
        crate::audit_bundle::create_bundle,
        upstream_sessions::list_sessions,
        upstream_sessions::revoke_session,
        oauth_consent::list_grants,
        oauth_consent::revoke_grant,
        catalog::list_servers,
        catalog::list_drift_events,
        catalog::approve_server,
        catalog::quarantine_server,
        policy_bundles::list_bundles,
        policy_bundles::active_bundle,
        policy_bundles::create_draft,
        policy_bundles::validate_bundle,
        policy_bundles::preview_simulate,
        policy_bundles::publish_bundle,
        policy_bundles::run_tests,
        policy_bundles::preview_impact,
        policy_bundles::rollback_bundle,
        manifest_bundles::list_bundles,
        manifest_bundles::active_bundle,
        manifest_bundles::create_draft,
        manifest_bundles::validate_bundle,
        manifest_bundles::publish_bundle,
        manifest_bundles::rollback_bundle,
        crate::approval_grants::create_grant,
        crate::approval_grants::list_grants,
        crate::approval_grants::revoke_grant,
        crate::approval_grants::list_codemode_approval_requests,
        crate::approval_grants::approve_codemode_request,
        crate::approval_grants::deny_codemode_request,
        rbac::list_roles,
        rbac::create_role,
        rbac::get_role,
        rbac::update_role,
        rbac::delete_role,
        rbac::list_assignments,
        rbac::create_assignment,
        rbac::delete_assignment,
        rbac::list_group_mappings,
        rbac::create_group_mapping,
        rbac::delete_group_mapping,
        tenants::list_tenants,
        tenants::create_tenant,
        tenants::get_tenant,
        tenants::update_tenant,
        tenants::delete_tenant,
        rate_limit_policies::list_policies,
        rate_limit_policies::create_policy,
        rate_limit_policies::get_policy,
        rate_limit_policies::update_policy,
        rate_limit_policies::delete_policy,
        api_key_profiles::list_profiles,
        api_key_profiles::create_profile,
        api_key_profiles::get_profile,
        api_key_profiles::delete_profile,
        break_glass::mint_token,
        break_glass::list_tokens,
        break_glass::revoke_token,
        change_requests::propose_request,
        change_requests::get_request_status,
        change_requests::get_request_secret,
        change_requests::list_requests,
        change_requests::approve_request,
        change_requests::deny_request,
        tasks::list_tasks,
        tasks::get_task,
        crate::codemode_executions::list_executions,
        crate::codemode_executions::cancel_execution,
        inspection_rules::list_rules,
        inspection_rules::create_rule,
        inspection_rules::get_rule,
        inspection_rules::update_rule,
        inspection_rules::delete_rule,
        federated_peers::list_peers,
        federated_peers::create_peer,
        federated_peers::get_peer,
        federated_peers::update_peer,
        federated_peers::delete_peer,
        confidential_clients::list_clients,
        confidential_clients::create_client,
        confidential_clients::delete_client,
    ),
    components(schemas(
        ApiErrorBody,
        servers::ServerSummary,
        builtins::BuiltinSurfaceView,
        builtins::BuiltinToolView,
        servers::ServerDetail,
        servers::ToolListResponse,
        servers::ToolView,
        servers::ReconnectResponse,
        servers::RefreshCatalogResponse,
        servers::QuarantineView,
        servers::ClearQuarantineResponse,
        policies::PoliciesResponse,
        policies::SimulateRequest,
        policies::SimulatePrincipal,
        policies::SimulateAction,
        policies::SimulateResource,
        policies::SimulateResponse,
        audit::AuditListResponse,
        waygate_storage::ChainVerifyReport,
        waygate_storage::ChainHead,
        waygate_storage::ChainMismatch,
        waygate_storage::ChainVerifyStatus,
        waygate_storage::MismatchKind,
        crate::audit_routing::RoutingRowView,
        crate::audit_routing::RoutingListResponse,
        crate::audit_routing::UpsertRoutingBody,
        crate::audit_retention::RetentionPolicyView,
        crate::audit_retention::RetentionListResponse,
        crate::audit_retention::UpsertRetentionBody,
        crate::audit_sweep::RunSweepBody,
        crate::audit_sweep::SweepReportView,
        crate::audit_bundle::CreateBundleBody,
        upstream_sessions::SessionRow,
        upstream_sessions::SessionListResponse,
        oauth_consent::GrantRow,
        oauth_consent::GrantListResponse,
        catalog::ServerListResponse,
        catalog::DriftListResponse,
        catalog::StatusChangeBody,
        crate::approval_grants::CreateGrantRequest,
        crate::approval_grants::GrantView,
        crate::approval_grants::GrantExecutionBindingView,
        crate::approval_grants::GrantListResponse,
        crate::approval_grants::CodeModeApprovalRequestView,
        crate::approval_grants::PendingCodeModeApprovalView,
        crate::approval_grants::PendingCodeModeApprovalList,
        crate::codemode_executions::OperatorExecutionView,
        crate::codemode_executions::OperatorExecutionList,
        crate::codemode_executions::CancelExecutionResponse,
        crate::approval_grants::CodeModeApprovalDecision,
        policy_bundles::BundleListResponse,
        policy_bundles::CreateDraftBody,
        policy_bundles::ValidateBundleBody,
        policy_bundles::ValidateBundleResponse,
        policy_bundles::PreviewSimulateBody,
        crate::impact::ImpactReport,
        crate::impact::ImpactDelta,
        crate::impact::ImpactSample,
        crate::impact::ReplayDecision,
        crate::policy_tests::PolicyTestCase,
        crate::policy_tests::ExpectedVerdict,
        crate::policy_tests::ExpectedDecision,
        crate::policy_tests::PolicyTestResult,
        crate::policy_tests::PolicyTestReport,
        policies::SimTraceEntry,
        waygate_policy::PolicyBundle,
        waygate_policy::PolicyBundleSummary,
        waygate_policy::PolicyStatus,
        manifest_bundles::ManifestBundleListResponse,
        manifest_bundles::ManifestCreateDraftBody,
        manifest_bundles::ManifestValidateBundleBody,
        manifest_bundles::ManifestValidateBundleResponse,
        waygate_manifest_store::ManifestBundle,
        waygate_manifest_store::ManifestBundleSummary,
        waygate_manifest_store::ManifestStatus,
        waygate_catalog::CatalogServerSummary,
        waygate_catalog::CatalogServerStatus,
        waygate_catalog::CatalogVisibility,
        waygate_catalog::DriftEvent,
        waygate_catalog::DriftSeverity,
        waygate_authz::PolicySnapshot,
        waygate_upstream::ToolClassification,
        waygate_mcp::protocol::RiskTier,
        waygate_storage::AuditRow,
        rbac::CreateRoleRequest,
        rbac::UpdateRoleRequest,
        rbac::CreateAssignmentRequest,
        rbac::CreateGroupMappingRequest,
        rbac::RoleListResponse,
        rbac::AssignmentListResponse,
        rbac::GroupMappingListResponse,
        waygate_rbac::Role,
        waygate_rbac::RoleAssignment,
        waygate_rbac::GroupRoleMapping,
        tenants::CreateTenantRequest,
        tenants::UpdateTenantRequest,
        tenants::TenantListResponse,
        tenants::TenantOnboardingResponse,
        tenants::OnboardingReport,
        tenants::SideEffectStatus,
        tenants::ScimApiKeyOutcome,
        waygate_tenants::Tenant,
        waygate_tenants::TenantStatus,
        rate_limit_policies::CreatePolicyRequest,
        rate_limit_policies::UpdatePolicyRequest,
        rate_limit_policies::PolicyListResponse,
        rate_limit_policies::PolicyView,
        waygate_quota::QuotaScope,
        waygate_quota::QuotaAction,
        api_key_profiles::CreateProfileRequest,
        api_key_profiles::ProfileListResponse,
        api_key_profiles::ProfileView,
        waygate_apikeys::Profile,
        break_glass::MintRequest,
        break_glass::TokenRow,
        break_glass::TokenListResponse,
        change_requests::ProposeRequest,
        change_requests::ProposeResponse,
        change_requests::StatusResponse,
        change_requests::ListResponse,
        change_requests::DenyRequest,
        change_requests::DecisionResponse,
        change_requests::SecretResponse,
        tasks::TaskListResponse,
        waygate_dashboard_stores::tasks::Task,
        waygate_dashboard_stores::tasks::TaskStatus,
        inspection_rules::CreateRuleRequest,
        inspection_rules::UpdateRuleRequest,
        inspection_rules::RuleListResponse,
        waygate_dashboard_stores::inspection_rules::InspectionRule,
        waygate_dashboard_stores::inspection_rules::InspectorKind,
        federated_peers::CreatePeerRequest,
        federated_peers::UpdatePeerRequest,
        federated_peers::PeerListResponse,
        waygate_federation::FederatedPeer,
        waygate_federation::TrustTier,
        confidential_clients::CreateClientRequest,
        confidential_clients::CreateClientResponse,
        confidential_clients::ClientSummary,
        confidential_clients::ClientListResponse,
    )),
    tags(
        (name = "servers", description = "Upstream MCP server catalog"),
        (name = "policies", description = "Cedar policy inspection + simulation"),
        (name = "server_manifests", description = "Version ledger for the on-disk servers/*.yaml set (list, active, validate, draft, publish, rollback)"),
        (name = "audit", description = "Paginated audit log"),
        (name = "upstream_sessions", description = "Tier-A durable upstream sessions (list metadata, revoke)"),
        (name = "oauth_consent", description = "OAuth consent grants per (tenant, principal, client)"),
        (name = "catalog", description = "Governed catalog read views (servers, drift events)"),
        (name = "policy_bundles", description = "Durable Cedar policy bundles (list, active, draft, publish)"),
        (name = "rbac", description = "RBAC roles, sub→role assignments, and SCIM group→role mappings"),
        (name = "tenants", description = "Canonical tenants registry"),
        (name = "rate_limit_policies", description = "Per-tenant token-bucket rate-limit policies"),
        (name = "api_key_profiles", description = "Per-tenant API-key mint profiles bounding scope/ttl/owner/reason"),
        (name = "break_glass", description = "Single-use override tokens that bypass Cedar Deny for incident response"),
        (name = "change_requests", description = "HITL control-plane: an automated caller proposes a privileged change (mcp:propose) and polls its status (CIBA-shaped); a human approves or denies, and execution runs server-side on approval"),
        (name = "tasks", description = "MCP Tasks primitive — long-running tool call state. Read-only persistence layer; InvocationService write-through and client subscribe are deferred until the spec stabilizes"),
        (name = "codemode_executions", description = "Operator view of in-flight Code Mode executions projected from the execution journal (identity, ownership, state, claim liveness, age — never program content), plus tenant-scoped cancellation"),
        (name = "inspection_rules", description = "Per-tenant response-inspector rule overrides layered on top of the built-in PII/secrets/poisoning rulesets; admin CRUD only until the runtime consumer lands"),
        (name = "federated_peers", description = "Federated gateway peer registry — operator-approved remote MCP gateways this gateway federates with (Tier-C identity chaining), backed by a JWKS fetcher and peer-assertion validator"),
    ),
)]
pub struct ApiDoc;

/// Build a router that serves the OpenAPI 3.1 JSON spec at
/// `/api/v1/openapi.json`. Intentionally unauthenticated — see module docs.
pub fn router() -> Router<()> {
    Router::new().route("/api/v1/openapi.json", get(spec_json))
}

async fn spec_json() -> Json<utoipa::openapi::OpenApi> {
    Json(ApiDoc::openapi())
}
